services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matcher
    ports: ['5433:5432']
    volumes:
      - matcher_pg:/var/lib/postgresql
      - ./src/database/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      retries: 10
volumes:
  matcher_pg:
